### ISSUE TITLE
Credits menu display issue

### ISSUE THREAD

**Issue by hakanto** [resonatecoop/stream2own#142]
From dev in email:

"I randomly noticed that the black or red "Credits" section of the menu displays a little weird because of a graphical bug in Firefox.

Even though this <input type="number" /> field is disabled, Firefox still wants to show the up/down arrows that they associate with that field type. They appear as ghostly background buttons behind the "Add Credits" button.

I would have submitted a PR to fix it, but I couldn't make instant sense of how your streaming player code displays things. I'd suggest adding:

input[type=number] {
-moz-appearance:textfield;
}

to your CSS per:
https://stackoverflow.com/questions/23372903/hide-up-down-arrow-buttons-spinner-in-input-number-firefox-29"

**Comment by peterklingelhofer** [comment]
Appears to be a duplicate issue here: #141.

**Comment by auggod** [comment]
Can fix using this css in components/header/index.css

```css
input[disabled][type=number] {
  -moz-appearance: textfield;
}
```

Should be part of next update.

**Comment by fgblomqvist** [comment]
@auggod Out of curiosity, is there a specific reason a number input is used rather than just plain text?

**Comment by auggod** [comment]
@fgblomqvist Just made sense to me semantically.

**Comment by fgblomqvist** [comment]
Alright. I'd say it might be more conventional/semantically correct to not use an input since the user can't actually input anything, and the task is just to display a value. That way you'd avoid any weird issues like this and you'd also avoid confusing screen readers (if accessibility is on the agenda). Either way, not trying to step on your toes, so potatoes potatos I suppose 🙃
