### ISSUE TITLE
Can't login after creating account without performing a password reset

### ISSUE THREAD

**Issue by gblomqvist** [resonatecoop/stream2own#151]
### Operating system
Linux

### Browser name and version
Firefox 88.0.1

### Expected behavior
After account creation it should be possible to login without first having to perform a password reset.

### Actual behavior
After account creation I couldn't login, despite waiting for days. I performed a password reset using **the same password I had initially used**, and then I could login.

### Steps to reproduce behavior
Create an account and try to login. In case the password used matters, I encountered the issue when using the following 64-character password:

    tnDxwtzZ5DLTcxab9pmEaSNjYHQbwqjBhnFDabKSEgizhrfcXWhK8sQR6UAz9tuv

(Of course I don't use this password any more.)

**Comment by fgblomqvist** [comment]
I think I experienced the same issue when I signed up a week or two ago, had to perform a reset to be able to login. Otherwise I got a message like "if you recently signed up, please wait a minute".

**Comment by auggod** [comment]
I am able to reproduce this issue no matter the password length. After disconnecting once I have been auto logged, I am not able to connect again either to the main website resonate.is or the player.
It seems the occurence of the problem is fairly recent. I don't think it's possible it was there for more than a month. 
It's clear the issue is with wordpress.

**Comment by vectorjohn** [comment]
I have a similar problem but it doesn't go away when I reset my password. It's only the player that I can't log in to, I can get in my account just fine. But the player says "If you just signed up or changed your password, please try again in a few seconds…"
I waited many thousands of seconds, and still no luck. I just reset again after reading this bug in case the issue was intermittent, but no luck.

**Comment by auggod** [comment]
Did you use your email or username to login on the website? On the player, it will ask only for your email, make sure this is the one you have registered with (including +)

**Comment by auggod** [comment]
We found out it was a configuration issue on the website. The system was configured to allow password less signups (to set password later).

**Comment by vectorjohn** [comment]
OK, that didn't solve my problem because like I said, I can't log in even after changing my password, I only get the "If you just signed up or changed your password, please try again in a few seconds…" forever (even after waiting overnight). I am using the same email which works to log into my account but not the player (you get a different error message if you try to use a username). 

Should this be a different issue, since it seems like the others are related to the configuration change?

**Comment by fgblomqvist** [comment]
Yes please create a separate issue so that we can close this one. But thanks for reporting 🙂.

**Comment by vectorjohn** [comment]
https://github.com/resonatecoop/stream/issues/161 created. And I discovered the cause, the player's login system fails with certain passwords that the account does not, so I was in a state where logging into account works but player fails, and the error message on the player is generic (same as if anyone types the wrong password).

**Comment by gblomqvist** [comment]
Sounds like this issue has been solved, great!

**Comment by hsandt** [comment]
I just got this issue today. I keep clicking on Login > Finish Login but then I'm back to the discover page with the Login button visible and "Login to listen to full song" message when I try to play anything.

OS: Ubuntu 22.04
Browser: Chrome

I'll try other browsers/sessions later for a fresh login...
