### ISSUE TITLE
Change .localhost to .is for API?

### ISSUE THREAD

**Issue by giraffekey** [resonatecoop/stream2own#47]
If you have the `API_DOMAIN` set to `api.resonate.localhost` the page displays "Failed to fetch artists" however if you change your `.env` file to have it set as `api.resonate.is` it loads the artists correctly. Is there any reason to still have it set to `.localhost` or should this be changed in `.env.example`?

**Comment by auggod** [comment]
The current api has yet to be open sourced. At least we plan to open source a 'v2' one that you could run locally.
So, for now you may just set api.resonate.is as the API_DOMAIN in your .env file.
For development, I only suggest to use *.resonate.localhost because it's always whitelisted in our CORS config. You may generate a self signed certificate for it too.
