### ISSUE TITLE
Migrate from lerna to npm 7 workspaces

### ISSUE THREAD

**Issue by auggod** [resonatecoop/stream2own#76]
Determine if migrating from lerna to npm 7 worspaces is a good idea. This will require some more experimentation on my end.

**Comment by fgblomqvist** [comment]
Is this something you'd still want help with? I'd be down to give it a shot. The main benefits I can see is one less dependency and more importantly, all the standard npm commands will work which means easier for new/old devs rather than learning/remembering lerna stuff. Or did you have any specific concerns?

**Comment by fgblomqvist** [comment]
Did some initial experimentation and one thing so far that would be lost is the convenience of the `lerna publish from-package` command. It would have to be replaced with another little script/dep if it's used.

**Comment by fgblomqvist** [comment]
Here's a branch where I attempted the migration (minus the publish script):
https://github.com/fgblomqvist/stream/tree/migrate-to-workspaces
Down to open a PR and discuss some things there, but can also respect if you decide that it's not worth it :slightly_smiling_face:

**Comment by fgblomqvist** [comment]
any thoughts on this @auggod?
